services:
  mongo:
    image: mongo:6.0
    container_name: mongo_db_mocky
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  app:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: docker_images/deploy/Dockerfile.app
    container_name: mocky
    env_file:
      - .envs/.env.docker
    ports:
      - "8002:8000"
    volumes:
      - .:/app

  testing:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: docker_images/testing/Dockerfile.testing
    container_name: mocky-testing
